
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sixeyed.MessageQueue.Integration.Data
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public User()
    {

        this.UserEvents = new HashSet<UserEvent>();

    }


    public int Id { get; set; }

    public string EmailAddress { get; set; }

    public bool IsUnsubscribed { get; set; }

    public Nullable<System.DateTime> UnsubscribedAt { get; set; }



    public virtual ICollection<UserEvent> UserEvents { get; set; }

}

}
